warning_threshold: 15

excluded:
- Pods

disabled_rules:
- trailing_whitespace

line_length: 120
type_body_length:
  warning: 300
  error: 400

function_parameter_count:
  warning: 10
  error: 15

file_length:
  warning: 500
